baseURL = "https://randallgoosby.com/"
theme = "raditian-free-hugo-theme"
DefaultContentLanguage = "en"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/flickity.css"
  [[params.plugins.css]]
  URL = "css/custom.css"
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/flickity.pkgd.min.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation



[params]

  sections = ["showcase", "about", "events", "releases", "videos", "gallery", "news", "contact", "newsletter"]

  googleTagManagerID = "G-MZLSRF6M3S" # Google Analytics works with Google Tag Manager but we goin w reg analytics babyyy

  main_sections = ["event"]


  [params.footer]
      [params.footer.radity_logo]
        x = "img/general/gg.png"
        _2x = "img/general/gg.png"
        alt = "Gina Goosby"

[Languages]
[Languages.en]
languageName = "ENGLISH"
languageCode = "en-us"
weight = 1
contentDir = 'content/en'
copyright = "© Randall Goosby. All rights reserved."
  
[Languages.en.params.logo]
  text1 = "RANDALL"
  text2 = "   GOOSBY"

[Languages.en.menu]
  [[Languages.en.menu.header]]
  name = "About"
  URL = "/#about"
  weight = 2

  [[Languages.en.menu.header]]
  name = "Events"
  URL = "/#events"
  weight = 3

  [[Languages.en.menu.header]]
  name = "News"
  URL = "/#news"
  weight = 4

  [[Languages.en.menu.header]]
  name = "Contact"
  URL = "/#contact"
  weight = 5

  [[Languages.en.menu.footer]]
  name = "About"
  URL = "/bio"
  weight = 2

  [[Languages.en.menu.footer]]
  name = "Events"
  URL = "/events"
  weight = 3

  [[Languages.en.menu.footer]]
  name = "News"
  URL = "/press"
  weight = 4

  [[Languages.en.menu.footer]]
  name = "Contact"
  URL = "/#contact"
  weight = 5
  
[Languages.jp]
languageName = "日本語"
languageCode = "ja-jp"
weight = 2
copyright = "© Randall Goosby. All rights reserved."

[Languages.jp.params.logo]
  text1 = "ランドル"
  text2 = "　グーズビー"

# navigation
[Languages.jp.menu]

  [[Languages.jp.menu.header]]
  name = "プロフィール"
  URL = "#about"
  weight = 2

  [[Languages.jp.menu.header]]
  name = "スケジュール"
  URL = "#events"
  weight = 3

  [[Languages.jp.menu.header]]
  name = "ニュース"
  URL = "#news"
  weight = 4

  [[Languages.jp.menu.header]]
  name = "コンタクト"
  URL = "#contact"
  weight = 5

  [[Languages.jp.menu.footer]]
  name = "プロフィール"
  URL = "jp/bio"
  weight = 2

  [[Languages.jp.menu.footer]]
  name = "スケジュール"
  URL = "events"
  weight = 3

  [[Languages.jp.menu.footer]]
  name = "ニュース"
  URL = "press"
  weight = 4

  [[Languages.jp.menu.footer]]
  name = "コンタクト"
  URL = "contact"
  weight = 5

[Languages.kr]
languageName = "한국어"
languageCode = "ko-kr"
weight = 3
contentDir = 'content/kr'
copyright = "© Randall Goosby. All rights reserved."

[Languages.kr.params.logo]
  text1 = "RANDALL"
  text2 = "　GOOSBY"

# navigation
[Languages.kr.menu]

  [[Languages.kr.menu.header]]
  name = "ABOUT"
  URL = "#about"
  weight = 2

  [[Languages.kr.menu.header]]
  name = "CONCERTS"
  URL = "#events"
  weight = 3

  [[Languages.kr.menu.header]]
  name = "NEWS"
  URL = "#news"
  weight = 4

  [[Languages.kr.menu.header]]
  name = "CONTACT"
  URL = "#contact"
  weight = 5

  [[Languages.kr.menu.footer]]
  name = "ABOUT"
  URL = "kr/bio"
  weight = 2

  [[Languages.kr.menu.footer]]
  name = "CONCERTS"
  URL = "events"
  weight = 3

  [[Languages.kr.menu.footer]]
  name = "NEWS"
  URL = "press"
  weight = 4

  [[Languages.kr.menu.footer]]
  name = "CONTACT"
  URL = "/#contact"
  weight = 5