baseURL = "https://randallgoosby.com/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/flickity.css"
  [[params.plugins.css]]
  URL = "css/custom.css"
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/flickity.pkgd.min.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "/#about"
  weight = 2

  [[menu.header]]
  name = "Events"
  URL = "/#events"
  weight = 3

  [[menu.header]]
  name = "News"
  URL = "/#news"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "/#contact"
  weight = 5

  [[menu.footer]]
  name = "About"
  URL = "/bio"
  weight = 2

  [[menu.footer]]
  name = "Events"
  URL = "/events"
  weight = 3

  [[menu.footer]]
  name = "News"
  URL = "/press"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "/contact"
  weight = 5


[params]

  sections = ["showcase", "about", "events", "releases", "videos", "gallery", "news", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  main_sections = ["event"]

  [params.logo]
    text1 = "RANDALL"
    text2 = "   GOOSBY"

  [params.footer]
      copyright = "© Randall Goosby. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/gg.png"
        _2x = "img/general/gg2x.png"
        alt = "Designed by Gina Goosby"